name = "flowtracer-license-api"
main = "cloudflare-worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
routes = [
  { pattern = "license.flowtracer.dev", custom_domain = true }
]
