const test = require('node:test');
const assert = require('node:assert');

// Mock 'vscode' module before loading LicenseManager
const Module = require('node:module');
const originalRequire = Module.prototype.require;
const mockMachineId = 'dev-machine-uuid-99999';

Module.prototype.require = function (id) {
  if (id === 'vscode') {
    return {
      env: {
        machineId: mockMachineId
      },
      commands: {
        executeCommand: async () => {}
      },
      window: {
        showInformationMessage: async () => {},
        showErrorMessage: async () => {},
        showWarningMessage: async () => {},
        showInputBox: async () => {}
      },
      ProgressLocation: { Notification: 15 }
    };
  }
  return originalRequire.apply(this, arguments);
};

const workerModule = require('../../../server/cloudflare-worker');
const worker = workerModule.default || workerModule;
const { LicenseManager } = require('../dist/license/LicenseManager');

const TEST_PRIVATE_KEY = `-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIBLtv8Hl+cf52ZTiUXArMzuiad0ENHJ7zG35z8S7jBuG
-----END PRIVATE KEY-----`;

const mockEnv = {
  POLAR_ACCESS_TOKEN: 'polar_test_token_xyz',
  POLAR_ORGANIZATION_ID: 'org_test_123',
  ED25519_PRIVATE_KEY: TEST_PRIVATE_KEY,
  DEV_BYPASS_KEY: 'FT-DEV-LOCAL-TEST'
};

test('CloudflareWorker: Health check returns ok status', async () => {
  const req = new Request('https://license.flowtracer.dev/health', {
    method: 'GET'
  });
  const res = await worker.fetch(req, mockEnv);
  assert.strictEqual(res.status, 200);
  const data = await res.json();
  assert.strictEqual(data.status, 'ok');
  assert.strictEqual(data.service, 'flowtracer-license-engine');
});

test('CloudflareWorker: Non-existent routes return 404', async () => {
  const req = new Request('https://license.flowtracer.dev/api/v1/invalid', {
    method: 'POST'
  });
  const res = await worker.fetch(req, mockEnv);
  assert.strictEqual(res.status, 404);
});

test('CloudflareWorker: Missing required fields in activation returns 400', async () => {
  const req = new Request('https://license.flowtracer.dev/api/v1/activate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ licenseKey: '' })
  });
  const res = await worker.fetch(req, mockEnv);
  assert.strictEqual(res.status, 400);
  const data = await res.json();
  assert.match(data.error, /Missing required fields/);
});

test('CloudflareWorker: Dev bypass key produces cryptographically valid token verifiable by LicenseManager', async () => {
  const req = new Request('https://license.flowtracer.dev/api/v1/activate', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      licenseKey: 'FT-DEV-LOCAL-TEST',
      machineId: mockMachineId,
      platform: 'darwin',
      appVersion: '0.1.0'
    })
  });

  const res = await worker.fetch(req, mockEnv);
  assert.strictEqual(res.status, 200);
  const data = await res.json();

  assert.strictEqual(data.valid, true);
  assert.strictEqual(data.payload.key, 'FT-DEV-LOCAL-TEST');
  assert.strictEqual(data.payload.machineId, mockMachineId);
  assert.strictEqual(data.payload.expiresAt, null); // Lifetime
  assert.ok(data.signature, 'Signature must be returned');

  // Verify the worker signature using LicenseManager's offline verification engine!
  const mockContext = {
    secrets: {
      get: async () => null,
      store: async () => {},
      delete: async () => {}
    },
    globalState: {
      get: () => null,
      update: async () => {}
    }
  };

  const lm = new LicenseManager(mockContext);
  // Store the worker-generated token directly
  await mockContext.secrets.store('flowtracer_pro_signed_token', JSON.stringify({
    payload: data.payload,
    signature: data.signature
  }));
  // Mock internal retrieval
  mockContext.secrets.get = async () => JSON.stringify({
    payload: data.payload,
    signature: data.signature
  });

  const isPro = await lm.isProUser();
  assert.strictEqual(isPro, true, 'LicenseManager must successfully verify the Ed25519 signature generated by the Cloudflare Worker');
});
